export const offers = [
  {
    id: "1",
    product_name: "Pastel de fresa",
    description: "Pastel con relleno de fresa",
    actual_price: 2.5,
    previous_price: 4,
    offer_duration: "Hasta agotar existencias",
    active: true,
    images: [
      {
        id: "1",
        url: "https://cdn7.kiwilimon.com/recetaimagen/16297/8238.jpg",
      },
      {
        id: "2",
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrwqkgSBiptFvqPfxnjy-W3uRyO6M5cdrpvcPARS_Q5w&s",
      },
    ],
    store: {
      idStore: "1",
      name: "Pastelería Francesa",
      description: "Venta de pasteles",
      latitude: 13,
      longitude: 14,
      departament: "San Salvador",
      municipality: "San Salvador",
      direction: "5ta calle poniente, Local #34",
      ownerName: undefined,
      website: undefined,
      phone: undefined,
      email: undefined,
    },
  },
  {
    id: "2",
    product_name: "Vestido",
    description: "Vestido formal",
    actual_price: 12,
    previous_price: 25,
    offer_duration: "25/06/2024",
    active: true,
    images: [
      {
        id: "3",
        url: "https://m.media-amazon.com/images/I/61BGXhz-IcL._AC_UY1000_DpWeblab_.jpg",
      },
    ],
    store: {
      idStore: "2",
      name: "Fashion store",
      description: "Venta de ropa nueva",
      latitude: 12,
      longitude: 13,
      departament: "La Libertad",
      municipality: "Antiguo Cuscatlán",
      direction: "25 calle sur, Edificio Nueva Vista, Local #3",
      ownerName: undefined,
      website: undefined,
      phone: undefined,
      email: undefined,
    },
  },
];
